version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run: make release VERSION=$(git describe)
      - persist_to_workspace:
          root: .
          paths:
            - build

  test:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash)

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            VERSION=$( ./build/dnaglider-linux -version )
            ghr -t "${GITHUB_TOKEN}" -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" -delete "${VERSION}" ./build/
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - build
      - publish-github-release:
          filters:
            branches:
              only: release
          requires:
            - build
            - test
